[2025-04-03T05:16:33.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-03T05:16:33.393+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schedule.expurgo_clientes manual__2025-04-03T05:16:26.926041+00:00 [queued]>
[2025-04-03T05:16:33.402+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schedule.expurgo_clientes manual__2025-04-03T05:16:26.926041+00:00 [queued]>
[2025-04-03T05:16:33.405+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-03T05:16:33.414+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): expurgo_clientes> on 2025-04-03 05:16:26.926041+00:00
[2025-04-03T05:16:33.420+0000] {standard_task_runner.py:72} INFO - Started process 1557 to run task
[2025-04-03T05:16:33.424+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'schedule', 'expurgo_clientes', 'manual__2025-04-03T05:16:26.926041+00:00', '--job-id', '2008', '--raw', '--subdir', 'DAGS_FOLDER/dag_master.py', '--cfg-path', '/tmp/tmp6lj2ezuq']
[2025-04-03T05:16:33.426+0000] {standard_task_runner.py:105} INFO - Job 2008: Subtask expurgo_clientes
[2025-04-03T05:16:33.450+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T05:16:33.486+0000] {task_command.py:467} INFO - Running <TaskInstance: schedule.expurgo_clientes manual__2025-04-03T05:16:26.926041+00:00 [running]> on host 11605a72ff70
[2025-04-03T05:16:33.562+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='schedule' AIRFLOW_CTX_TASK_ID='expurgo_clientes' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T05:16:26.926041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T05:16:26.926041+00:00'
[2025-04-03T05:16:33.563+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-03T05:16:33.572+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-03T05:16:33.573+0000] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'docker exec linux_python /bin/bash -c \'/workspace/scripts/expurgo_server.sh /path/to/move_cloud/clientes/ && echo "Script Executado com Sucesso!"\'']
[2025-04-03T05:16:33.579+0000] {subprocess.py:99} INFO - Output:
[2025-04-03T05:16:33.681+0000] {subprocess.py:106} INFO - Verificando diretorio: /path/to/move_cloud/clientes/
[2025-04-03T05:16:33.682+0000] {subprocess.py:106} INFO - Conteúdo do diretório antes da limpeza:
[2025-04-03T05:16:33.684+0000] {subprocess.py:106} INFO - clientes.csv
[2025-04-03T05:16:33.685+0000] {subprocess.py:106} INFO - Apagando itens do diretório...
[2025-04-03T05:16:33.686+0000] {subprocess.py:106} INFO - Verificando se o diretório está vazio...
[2025-04-03T05:16:33.687+0000] {subprocess.py:106} INFO - O diretório está vazio.
[2025-04-03T05:16:33.688+0000] {subprocess.py:106} INFO - Script Executado com Sucesso!
[2025-04-03T05:16:33.694+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-03T05:16:33.717+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-03T05:16:33.718+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=schedule, task_id=expurgo_clientes, run_id=manual__2025-04-03T05:16:26.926041+00:00, execution_date=20250403T051626, start_date=20250403T051633, end_date=20250403T051633
[2025-04-03T05:16:33.776+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-03T05:16:33.807+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-03T05:16:33.808+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
